default:
	gcc main.c -o a.out

cs: client server

client: client.c
	gcc client.c -o client

server: server.c
	gcc server.c -o server

hs:
	gcc http_server.c -o hs

hc:
	gcc http_client.c -o hc

es: echo_server.c
	gcc echo_server.c -o es

ec: echo_client.c
	gcc echo_client.c -o ec
