# Author: amoblin@gmail.com
#
whoomin:
	@pdflatex whoomin.tex > /dev/null
	@make clean

amoblin:
	@pdflatex amoblin.tex > /dev/null
	@make clean
	
clean:
	rm *.aux *.out *.log

upload:
	cp amoblin.pdf ~/Everbox/
	cp amoblin.pdf ~/Dropbox/Public/
	cp whoomin.pdf ~/Everbox/
